#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2
module load R

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# core diversity analysis
time alpha_diversity.py -i ~/2018_02_smb/otus3/CoreBiom/core_table_100.biom -o ~/2018_02_smb/otus3/core100/adiv/adiv_shan.txt -m shannon,observed_otus,observed_species #PD_whole_tree,chao1,observed_otus,shannon #,observed_species #1-t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt 

# deactivating environment
source deactivate
