#!/bin/bash
#BATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

#Load modules
module load eb
module load Miniconda2

# loading virtualenv
source activate qiime1

# setting temporary directory
export TMPDIR=~/qiime_tmp

# picking closed reference otus
echo "Picking closed OTUs"
time pick_closed_reference_otus.py -i ~/2018_02_smb/sloutjoin/seqs.fna -o ~/2018_02_smb/otus3/ -r ~/SILVA_128_QIIME_release/rep_set/rep_set_16S_only/97/97_otus_16S.fasta -t ~/SILVA_128_QIIME_release/taxonomy/16S_only/97/majority_taxonomy_all_levels.txt -a -O 16

# summarise to make readable
echo "Summarising table"
time biom summarize -i ~/2018_02_smb/otus3/otu_table.biom

# deactivating environment
source deactivate
